name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build Xamarin.iOS
      run: msbuild /restore ./XamTrack.iOS/XamTrack.iOS.csproj /p:Platform=iPhoneSimulator /p:Configuration=Debug
    
    - name: Build Xamarin.Android
      run: msbuild /restore ./XamTrack.Android/XamTrack.Android.csproj /p:Configuration=Debug
      
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - shell: bash
      env:
        DpsIdScope: ${{ secrets.DpsIdScope }},
        IotHubConnectionString:  ${{ secrets.IotHubConnectionString }},
        DpsSymetricKey: ${{ secrets.DpsSymetricKey }},
        SharedKey: ${{ secrets.SharedKey }}
      run: |
        #REMEMBER TO SETUP PIPELINE VARIABLE
          if [ ! -n $(DpsIdScope) ]
          then
              echo "You need define the DpsIdScope variable in VSTS"
              exit
          fi
          
          #PATH TO CONSTANTS FILE
          APP_CONSTANT_FILE=XamTrack.Core/appconfig.json
          
          if [ -e "$APP_CONSTANT_FILE" ]
          then
              echo "Updating App Secret Values to DpsIdScope in appconfig.json"
              sed -i '' 's#"DpsIdScope": "[a-z:./\\_]*"#"DpsIdScope": "$DpsIdScope"#' $APP_CONSTANT_FILE
          
              echo "Updating App Secret Values to IotHubConnectionString in appconfig.json"
              sed -i '' 's#"IotHubConnectionString": "[a-z:./\\_]*"#"IotHubConnectionString": "$IotHubConnectionString"#' $APP_CONSTANT_FILE
          
              echo "Updating App Secret Values to DpsSymetricKey in appconfig.json"
              sed -i '' 's#"DpsSymetricKey": "[a-z:./\\_]*"#"DpsSymetricKey": "$DpsSymetricKey"#' $APP_CONSTANT_FILE
          
              echo "Updating App Secret Values to SharedKey in appconfig.json"
              sed -i '' 's#"SharedKey": "[a-z:./\\_]*"#"SharedKey": "$SharedKey"#' $APP_CONSTANT_FILE
          
              echo "File content:"
              cat $APP_CONSTANT_FILE
          fi
    
    - name: Run Test
      run: dotnet test ./XamTrack.Tests/XamTrack.Tests.csproj
