name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Xamarin.iOS
      run: msbuild ./XamTrack.iOS/XamTrack.iOS.csproj /p:Platform=iPhoneSimulator /p:Configuration=Debug
    
    - name: Build Xamarin.Android
      run: msbuild ./XamTrack.Android/XamTrack.Android.csproj /p:Configuration=Debug
      
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run Test
      run: dotnet test ./XamTrack.Tests/XamTrack.Tests.csproj
